SHELL = /bin/bash

views: clinical-features/*.sql demographics/*.sql severity-scores/*.sql
	bash build-views.sh

cohort: cohort.sql
	pgh=${PGHOST:-false}
	pgp=${PGPORT:-false}
	make clean-log
	bash build-cohort.sh 
		-h $pgh 
		-p $pgp
		-d "mimic"
		-s "mimiciii"
	 && bash build-views.sh

export: 
	bash bin/export-cohort.sh
	&& bash bin/export-views.sh

clean:
	read -p "Do you want to delete all files in data/cohort-build files [Y/n]?"  ures
	case $ures in
		[Yy]) 
			rm -rf data/cohort-build 
			&& mkdir data/cohort-build
			&& exit 0; break;;
		*) 
			echo "No action taken. Please enter Yes or no."
			exit 0;;
	esac
	exit 1

clean-log:
	make-build.log < EOM
	#########################################
	#            Bauer2017-pgSQL            #                 
	#   github.com/chebuu/Bauer2017-pgSQL   #
	#########################################

	#   Autogenerated by GNU make utility   #
	EOM