--         **PATIENTS**
-- | Name        | Postgres data type |
-- | ----------- | -----------------: |
-- | ROW_ID	     | INT                |
-- | SUBJECT_ID	 | INT                |
-- | GENDER	     | VARCHAR(5)         |
-- | DOB	       | TIMESTAMP(0)       |
-- | DOD	       | TIMESTAMP(0)       |
-- | DOD_HOSP	   | TIMESTAMP(0)       |
-- | DOD_SSN	   | TIMESTAMP(0)       |
-- | EXPIRE_FLAG | VARCHAR(5)         |